version: '3'

services:
  app:
    image: docker.muehlemann-popp.ch/goetterstammbaum:2
    ports:
      - 9090:9090
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:3.0
    environment:
      - NEO4J_AUTH=neo4j/coffy
    ports:
      - 7474:7474
      - 7687:7687
